source exercises/controls/id.sh
source exercises/controls/type.sh
source exercises/controls/category.sh
source exercises/controls/stream-name.sh
source exercises/controls/data.sh
source exercises/controls/write-message.sh
source exercises/controls/write-message-with-metadata.sh
source exercises/controls/get-stream-messages.sh
source exercises/controls/get-category-messages.sh
